### ISSUE TITLE
Day 16

### ISSUE THREAD

**Issue by joncol** [1Computer1/advent2022#1]
Hi, I found your AoC solution via reddit. I'm really interested in hearing some explaining words about your day 16 solution. Any chance you might provide that? I'm also looking into using `fgl` for this, but not really getting much of anywhere :confounded:.

**Comment by 1Computer1** [comment]
Hi! The solution works like this:

1. Build the graph via `fgl` (using a fold starting from `empty` and doing `insNode` and `insEdges` then using `undir` to make it undirected). I made the node labels be the flow rate but it that never actually gets used.
2. For each node, used `bft` to get the length of the path to every other node and built an adjacency map from that.
3. Consider only the nodes with positive flow rate (at this point I don't need the graph anymore, so we just have the maps; so far this is just the `parse` function).
4. The `stateTree` function is next and it basically just tries all possible paths through the valves with positive flow rate, keeping track of the time, the current location, and the already activated valves (along with how much flow they will have produced). This uses `unfoldTree` but it might as well could be a normal recursive function that concats since I end up calling `flatten` later on. The `withPath` function gives the path taken, though that also could be inlined into the above.
5. Got the maximums with `bestBySubset` (subset meaning the valves taken) and then maximum of that for part 1. For part 2, find two disjoint subsets that give the maximum.
